---
# Here we have the following setup:
# - Workstation Pro is installed on a Windows Host
# - A Windows VM is hosted on it
# Very simple playbook which boot the VM and run Windows updates

- hosts: windows-host
  gather_facts: no
  collections:
    - qsypoq.vmware_desktop
  tasks:

    - name: "Start the VM"
      win_vmware_desktop_power:
        target_vm_name: "Windows 10 Enterprise - Docker"
        state: "on"
        username: "API-USERNAME"
        password: "API-PASSWORD"

- hosts: windows-docker
  gather_facts: no
  tasks:

    - name: "Wait for system to become reachable"
      wait_for_connection:

    - name: "Gather facts for first time"
      setup:

    - name: "Create logs folder"
      win_file:
        path: C:\WindowsUpdatesLogs
        state: directory

    - name: "Install all updates with automatic reboots"
      win_updates:
        category_names: [ 'Application', 'Connectors', 'Critical Updates', 'Definition Updates', 'Developer Kits', 'Feature Packs', 'Guidance', 'Security Updates', 'Service Packs', 'Tools', 'Update Rollups', 'Updates']
        log_path: C:\WindowsUpdatesLogs\{{ ansible_facts['date_time']['epoch'] }}.txt
        reboot: yes
        reboot_timeout: 300